# Generated by Django 5.0.7 on 2024-08-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='trials_left',
            field=models.IntegerField(default=7),
        ),
    ]
