# Generated by Django 5.1 on 2024-08-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='free_trials',
            field=models.IntegerField(default=5),
        ),
    ]
