const TermsOfUse = () => {
    return (
        <>
            {/* Hero Section */}
            <div className="relative w-full h-[750px] flex items-center justify-center text-center text-white bg-cover bg-center bg-no-repeat"
                style={{ backgroundImage: "url('/privacy-policy-ct.png')" }}
            >
                <div className="relative z-10 px-8">
                    <h1 className="text-5xl font-bold">TERMS OF SERVICE</h1>
                    <p className="mt-4 max-w-3xl mx-auto text-lg">
                        Welcome to Ctrl Threats! These Terms of Service outline the rules and regulations for using our website and Products.
                    </p>
                </div>
            </div>
            <div className="flex flex-col min-h-screen bg-white">
                {/* Content Section */}
                <section className="max-w-6xl mx-auto py-14 px-2 text-gray-800">
                    <h1 className="text-2xl font-semibold mb-4">Acceptance of Terms</h1>
                    <p className="mb-8">
                        By accessing or using Ctrl Threats and its Products (including Ctrl Fake, DeepDetect, and ContentShield), you agree to comply with and be bound by these Terms of Service. If you do not agree with any part of these terms, please refrain from using our services.
                    </p>

                    <h1 className="text-2xl font-semibold mt-6">User Responsibilities</h1>
                    <p className="mt-2">
                        As a user of Ctrl Threats, you agree to:
                    </p>
                    <ul className="list-disc pl-6 mt-3 space-y-2 text-gray-700">
                        <li>Use our Products only for lawful purposes.</li>
                        <li>Not engage in unauthorized data scraping, hacking, or other disruptive activities.</li>
                        <li>Respect the intellectual property rights of Ctrl Threats and third parties.</li>
                    </ul>

                    <h1 className="text-2xl font-semibold mt-6">Account Registration</h1>
                    <p className="mt-2">
                        To access certain features, you may be required to create an account. You are responsible for safeguarding your account credentials and ensuring their confidentiality.
                    </p>

                    <h1 className="text-2xl font-semibold mt-6">Payment and Subscription</h1>
                    <p className="mt-2">
                        Some Ctrl Threats services require a paid subscription. By subscribing, you agree to:
                    </p>
                    <ul className="list-disc pl-6 mt-3 space-y-2 text-gray-700">
                        <li>Provide accurate payment information.</li>
                        <li>Authorize us to charge your selected payment method for fees associated with the service.</li>
                        <li>Cancel subscriptions before the next billing cycle if you do not wish to continue.
                        </li>
                    </ul>

                    <h1 className="text-2xl font-semibold mt-6">Intellectual Property</h1>
                    <p className="mt-2">
                        All content, trademarks, and technology associated with Ctrl Threats are the property of Ctrl Threats. You may not copy, modify, distribute, or use any of our intellectual property without prior written consent.
                    </p>

                    <h1 className="text-2xl font-semibold mt-6">Limitation of Liability</h1>
                    <p className="mt-2">
                        Ctrl Threats is not liable for:
                    </p>
                    <ul className="list-disc pl-6 mt-3 space-y-2 text-gray-700">
                        <li>Any indirect, incidental, or consequential damages resulting from the use of our services.</li>
                        <li>Data loss or service interruptions.</li>
                        <li>Content accuracy or reliability of results generated by our Products.</li>
                    </ul>

                    <h1 className="text-2xl font-semibold mt-6">Termination</h1>
                    <p className="mt-2">
                        Ctrl Threats reserves the right to suspend or terminate access to its services if a user violates these Terms of Service or engages in harmful activities.
                    </p>

                    <h1 className="text-2xl font-semibold mt-6">Governing Law</h1>
                    <p className="mt-2">
                        These terms shall be governed by and interpreted in accordance with the laws of the jurisdiction where Ctrl Threats operates.
                    </p>

                    <h1 className="text-2xl font-semibold mt-6">Changes to Terms</h1>
                    <p className="mt-2">
                        Ctrl Threats may update these Terms of Service at any time. Users will be notified of significant changes, and continued use of our services after updates signifies agreement to the revised terms.
                    </p>

                    <h1 className="text-2xl font-semibold mt-6">Contact Us</h1>
                    <p className="mt-4">
                        If you have any questions about these Terms of Service, contact us at:
                        <a href="mailto:support@ctrlthreats.com" className="text-[#6100FF] hover:underline"> support@ctrlthreats.com</a>.
                    </p>
                </section>
            </div>
        </>
    )
}

export default TermsOfUse