# Generated by Django 5.0.7 on 2024-10-07 07:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='temp_images/')),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.TextField(max_length=255, unique=True)),
            ],
        ),
    ]
