# Generated by Django 5.0.7 on 2024-10-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.TextField(default='iugc', max_length=255),
        ),
    ]
