# Generated by Django 5.0.7 on 2024-10-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='meta_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
