# Generated by Django 5.0.7 on 2024-10-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blog_meta_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='temp_images/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='content_image_1_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='temp_images/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='content_image_2_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
